Repository karenzindars/website, pull requests merged in 2021-02, with the labels that each got.

#1 Add Website Code
  .gitignore
  website/package-lock.json
  website/package.json
  website/public/favicon.ico
  website/public/img/bfam-diagram.png
  website/public/img/cool-rocks.jpg
  website/public/img/errbody-gettin-down.jpeg
  website/public/img/f-method.png
  website/public/img/group-photo.jpg
  website/public/img/karen-ballet.jpg
  website/public/img/karen-doin-thangs.jpg
  website/public/img/karen-garden.jpg
  website/public/index.html
  website/src/Components/Common/About.js
  website/src/Components/Common/Classes.js
  website/src/Components/Common/Contact.js
  website/src/Components/Common/ContinuingEducationCourses.js
  website/src/Components/Common/GroupClasses.js
  website/src/Components/Common/Home.js
  website/src/Components/Common/Mentoring.js
  website/src/Components/Common/MentoringSchedule.js
  website/src/Components/Common/Sessions.js
  website/src/Components/ContentWrapper/CalendarSideBar.js
  website/src/Components/ContentWrapper/ContentWrapper.js
  website/src/Components/ContentWrapper/KzHeader.js
  website/src/Components/ContentWrapper/Navbar.js
  website/src/Components/ContentWrapper/pattern.png
  website/src/Routing.js
  website/src/index.css
  website/src/index.js
Labels: enhancement

#2 Add minified files
  asset-manifest.json
  favicon.ico
  img/bfam-diagram.png
  img/cool-rocks.jpg
  img/errbody-gettin-down.jpeg
  img/f-method.png
  img/group-photo.jpg
  img/karen-ballet.jpg
  img/karen-doin-thangs.jpg
  img/karen-garden.jpg
  index.html
  static/css/main.23404fb1.chunk.css
  static/css/main.23404fb1.chunk.css.map
  static/js/2.879195eb.chunk.js
  static/js/2.879195eb.chunk.js.LICENSE.txt
  static/js/2.879195eb.chunk.js.map
  static/js/main.fba48418.chunk.js
  static/js/main.fba48418.chunk.js.map
  static/js/runtime-main.36ea4669.js
  static/js/runtime-main.36ea4669.js.map
  static/media/pattern.c2a9e86c.png
Labels: enhancement

#3 Correct title on website
  index.html
Labels: enhancement

#6 Use hashes in routes now
  asset-manifest.json
  index.html
  static/js/main.4bee4f07.chunk.js
  static/js/main.4bee4f07.chunk.js.map
  static/js/main.781a55f8.chunk.js
  static/js/main.781a55f8.chunk.js.map
  website/src/Components/Common/Classes.js
  website/src/Components/Common/Home.js
  website/src/Components/Common/Sessions.js
  website/src/Components/ContentWrapper/CalendarSideBar.js
  website/src/Components/ContentWrapper/Navbar.js
Labels: bug, enhancement

#8 Add build script + use https in minified code
  asset-manifest.json
  index.html
  rebuild-website.sh
  static/css/main.57794d22.chunk.css
  static/js/2.8842abe4.chunk.js
  static/js/2.8842abe4.chunk.js.map
  static/js/main.582f6e5d.chunk.js
  static/js/runtime-main.28249f9f.js
  static/js/runtime-main.28249f9f.js.map
  website/package.json
Labels: bug
